name: agronomek_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  connectivity_plus: ^1.4.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  flutter_spinkit: ^5.1.0
  splashscreen: ^1.3.5
  smooth_page_indicator: ^1.0.0+2
  google_maps_flutter: ^2.1.7
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.3.2
  firebase_core: ^1.20.0
  firebase_auth:
  flutter_facebook_auth:
  cool_alert: ^1.1.0
  mobile_scanner: ^2.0.0
  jwt_decode: ^0.3.1
  http: ^0.13.4
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  outline_gradient_button: ^2.0.0+1
  firebase_database: ^9.0.20
  slide_to_act: ^2.0.1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  flutter_speed_dial: ^6.0.0
  lottie: ^1.2.1
  syncfusion_flutter_charts: ^19.4.47
  intl: ^0.17.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/anims/
    - assets/images/
    - assets/images/AgronoMek.png
   
  fonts:
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/robotoslabmedium500.ttf
          weight: 500
        - asset: assets/fonts/robotoslabregular400.ttf
          weight: 400

    - family: Roboto Condensed
      fonts: 
        - asset: assets/fonts/robotocondensedregular400.ttf
          weight: 400
    - family: Amaranth
      fonts:
        - asset: assets/fonts/amaranthregular400.ttf
          weight: 400
        - asset: assets/fonts/amaranthbold700.ttf
          weight: 700